server:
  port: 8081
spring:
  name: products-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_PATH:jdbc:postgresql://localhost:5555/products}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group-1
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: com.andrbezr2016.products.kafka.ProductNotificationDeserializer